server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gd?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

